ConfigurationWeb/Controllers/DBController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Configuration.Data.Models;
using Microsoft.Extensions.Configuration;

namespace Configuration.Web.Controllers
{
    public class DBController : Controller
    {
        IConfiguration _configuration;

        public DBController(IConfiguration configuration)
        {
            _configuration = configuration;
        }


        /// <summary>
        /// Reading info from a custom DataBase configuration provider (DBConfigurationProvider) added in Program class
        /// </summary>
        /// <returns></returns>
        public IActionResult Index()
        {

            //Bind the config info into a Dictionary<string, string> object to pass it to the view
            var appInfo = new Dictionary<string, string>();
            appInfo.Add("ASPNETCORE_ENVIRONMENT", _configuration.GetValue<string>("ASPNETCORE_ENVIRONMENT"));
            appInfo.Add("http", _configuration.GetValue<string>("http"));
            appInfo.Add("https", _configuration.GetValue<string>("https"));
            appInfo.Add("Open Ports", _configuration.GetValue<string>("Open Ports"));
            appInfo.Add("sslPort", _configuration.GetValue<string>("sslPort"));
            appInfo.Add("TestUser", _configuration.GetValue<string>("TestUser"));
            appInfo.Add("TestUserGuid", _configuration.GetValue<string>("TestUserGuid"));
            appInfo.Add("ConfigurationConnectionStringDB", _configuration.GetValue<string>("ConfigurationConnectionStringDB"));

            return View(appInfo);
        }

        /// <summary>
        /// Reading configuration from app configuration, and loading into Person object
        /// </summary>
        /// <returns>Person</returns>
        [Route("complex")]
        [Route("[controller]/ComplexObject")]
        public ActionResult ComplexObject()
        {
            //Bind the config info into a model POCO object (Person) to pass it to the view
            var complexObject = _configuration.GetSection("Complex").Get<Person>();

            return View(complexObject);
        }

        /// <summary>
        /// Reading configuration from app configuration, and loading into List<Department> object
        /// </summary>
        /// <returns>List<Department></returns>
        [Route("departments")]
        [Route("[controller]/departments")]
        public ActionResult Departments()
        {
            var departments = _configuration.GetSection("Complex:Departments").GetChildren();
            var departmentsList = new List<Department>();
            foreach (var item in departments)
            {
                departmentsList.Add(new Department { Name = item.Key, Description = item.Value });
            }

            return View(departmentsList);
        }

        /// <summary>
        /// Information page describing how to read configuration from a database
        /// </summary>
        /// <returns></returns>
        [Route("dbinfo")]
        [Route("[controller]/DBInfo")]
        public IActionResult DBInfo()
        {
            return View();
        }
    }
}

ConfigurationWeb/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ConfigurationWeb.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;

namespace ConfigurationWeb.Controllers
{
    public class HomeController : Controller
    {
        private IConfiguration _configuration;

        //inject IConfiguration into controller to access the configuration
        public HomeController(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public IActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Loading a Configuration file section into a class
        /// </summary>
        /// <returns>ContactViewModel</returns>
        public IActionResult Contact()
        {
            //Bind the config info into a viewmodel object to pass it to the view
            var contact = _configuration.GetSection("Contact").Get<ContactViewModel>();
            
            return View(contact);
        }

        /// <summary>
        /// Load a Configuration file into a class
        /// </summary>
        /// <returns>List<ContactViewModel></returns>
        public IActionResult Team()
        {
            var team = _configuration.GetSection("Team").Get<List<ContactViewModel>>();

            return View(team);
        }

        /// <summary>
        /// Read info from contructor injected configuration (IConfiguration _configuration)
        /// Info comes from a custom configuration file (appsettings.CustomerInfo.json) added in Program.ConfigureAppConfiguration()
        /// Info is loaded into a viewmodel object to pass it to the view
        /// </summary>
        /// <returns>CustomerInfoViewModel</returns>
        public IActionResult Customer()
        {
            //Bind the config info into a viewmodel object to pass it to the view
            var customer = _configuration.GetSection("Customer").Get<CustomerInfoViewModel>();

            return View(customer);
        }

        public IActionResult Test()
        {
            return View();
        }

        /// <summary>
        /// Read info from contructor injected configuration (IConfiguration _configuration) and load it into ViewData objects for the view.
        /// </summary>
        /// <returns>ViewResult[""]</returns>
        public IActionResult Info()
        {
            ViewData["Message"] = _configuration["Message"].ToString();
            ViewData["InfoMessage"] = _configuration.GetValue<string>("InfoMessage", "An error has ocurred");

            return View();
        }

        /// <summary>
        /// Read info from contructor injected configuration (IConfiguration _configuration) and load it into ViewData objects for the view.
        /// </summary>
        /// <returns>ViewResult[""]</returns>
        public IActionResult Info2()
        {
            ViewData["Message"] = _configuration["Message"].ToString();
            ViewData["InfoMessage"] = _configuration.GetValue<string>("InfoMessage", "An error has ocurred");

            return View();
        }

    }
}

ConfigurationWeb/ViewComponents/CodeViewComponent.cs
using Configuration.Web.CustomConfiguration;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Configuration.Web.ViewComponents
{
    public class CodeViewComponent: ViewComponent
    {
        public CodeViewComponent()
        {

        }

        public IViewComponentResult Invoke(string name)
        {
            return View(name);
        }
    }
}

ConfigurationWeb/Views/DB/ComplexObject.cshtml
@model Configuration.Data.Models.Person

@{
    ViewData["Title"] = "Complex Object";
}

<div class="info-row">

    <div class="info-col">

        <h2 class="configuration_info_title">DB configuration - loading a Complex Object:</h2>

        <div class="configuration_info">
            <p>

                After loading all the configuration information from the database into the app configuration through the <code>Program</code> class, in its
                <code>CreateWebHostBuilder().ConfigureAppConfiguration</code> method while the app is starting up, as described
                <a asp-controller="DB" asp-action="DBInfo">here</a>, it is available for the application to use as any other loaded configuration.
            </p>
            <p>
                Then the configuration info can be used from anywhere in the app, by injecting a configuration (<code>IConfiguration _configuration</code>) object into the class constructor. 
                From there the info is available to be used throughout the class.
            </p>
            <p>
                For rendering, the configuration info is loaded here by injecting an <code>IConfiguration</code> object to the controller constructor and loading the info into a
                <code>Person</code> POCO object, using the <code>_configuration.GetSection("Complex").Get<<text>Person</text>>();</code> method (<code>.Get<<text>Person</text>>()</code> 
                binds the result to the <code>Person</code> class, and passing the dictionary object to the view.
            </p>
        </div>

    </div>

    <div class="info-col info-col-card">

        <div class="card-size">
            <div class="card-header">
                <h5><b>DB configuration - loading a Complex Object:</b></h5>
            </div>
            <div class="card-body">

                <p class="list-group-item"><b>Name: </b>@Model.Name</p>
                <p class="list-group-item"><b>Email: </b> @Model.Email</p>
                <p class="list-group-item"><b>Position: </b> @Model.Position</p>
                <p class="list-group-item">
                    <b>Address: </b> <br />
                    @Model.Address.Street <br />
                    @Model.Address.City, @Model.Address.Zipcode &nbsp; @Model.Address.Country
                </p>
                <p class="list-group-item">
                    <b>Department: </b> <br />
                    @Model.Department.Name - <cite> @Model.Department.Description </cite>
                </p>

            </div>
        </div>

    </div>

</div>

ConfigurationWeb/Views/DB/DBInfo.cshtml
@{
    ViewData["Title"] = "Configuration from a database";
}

@*<p><a data-toggle="modal" href="#DBConfigurationProviderModal"><code>DBConfigurationProvider</code></a></p>
    <p><a data-toggle="modal" href="#DBConfigurationSourceModal"><code>DBConfigurationSource</code></a></p>
    <p><a data-toggle="modal" href="#DBConfigurationSourceExtensionsModal"><code>DBConfigurationSourceExtensions</code></a></p>
    <p><a data-toggle="modal" href="#ProgramModal"><code>Program</code></a></p>*@

<h2 class="configuration_info_title">Reading ASP.NET Core 2 app Configuration from a database:</h2>

<div class="info-row">

    <div class="info-col-fullrow">

        <h4 class="configuration_info_title">Introduction:</h4>

        <div class="configuration_info">

            <p>All configuration in ASP.NET Core is based around the following building blocks: Configuration Sources, Providers, Sections and Settings.</p>
            <ul>
                <li>
                    <u>Configuration Sources</u> are configuration storage sources, such as a file (JSON, XML, ini), environment variables, a database or a Key Vault (secrets).
                </li>
                <li>
                    <u>Configuration Providers</u> contain the logic to retrieve the configuration settings from a configuration source, and then providing these settings as Key/Value pairs
                    to be used. In this section we will custom implement a database configuration provider to store/read our configuration from this database.
                </li>
                <li>
                    <u>Configuration Sections</u> allow the grouping of values into named sections.
                </li>
            </ul>


        </div>

    </div>
</div>


<div class="info-row">

    <div class="info-col">

        @await Component.InvokeAsync("Code", "DBConfigurationProvider")

        <h4 class="configuration_info_title">1. Configuration Provider:</h4>

        <div class="configuration_info">
            <p>
                Our configuration provider (<a data-toggle="modal" href="#DBConfigurationProviderModal"><code>DBConfigurationProvider</code></a>) contains all the logic to access the configuration information at run-time. Like any other configuration
                provider it has to implement <code>IConfigurationProvider</code> (in our case, its helper class <code>ConfigurationProvider</code>). Mostly all we have to do is:
            </p>
            <ol>
                <li>
                    In the constructor of our <code>DBConfigurationProvider</code> class inject a <code>DbContextOptions</code> object (<code>Action<<text>DbContextOptionsBuilder</text>> dbContextOptions</code>),
                    which is necessary to instantiate our <code>DbContext</code> class (<code>ConfigurationContext</code>).
                </li>
                <li>
                    Override the <code>ConfigurationProvider.Load()</code> method, where we’ll read all the configuration stored in <code>ConfigurationContext</code>, and load it into a local
                    dictionary object (<code>Data</code>).
                </li>
            </ol>

        </div>
    </div>
    <div class="info-col">

        @await Component.InvokeAsync("Code", "DBConfigurationSource")

        <h4 class="configuration_info_title">2. Configuration Source:</h4>

        <div class="configuration_info">
            <p>
                Now our configuration information can be read and loaded into the app configuration. The next step is to create a Configuration Source
                (<a data-toggle="modal" href="#DBConfigurationSourceModal"><code>DBConfigurationSource</code></a>) to build our Configurator Provider
                (<code>DBConfigurationProvider</code>) to make it available to the application.
            </p>
            <p>
                In our <code>DBConfigurationSource</code> class we will override the <code>Build()</code> method of the <code>IConfigurationSource</code> class that our config source must
                extend. <code>Build()</code> returns a new instance of our <code>DBConfigurationProvider</code> class.
            </p>
        </div>
    </div>
</div>


<div class="info-row">

    <div class="info-col">

        @await Component.InvokeAsync("Code", "DBConfigurationSourceExtensions")

        <h4 class="configuration_info_title">3. Configuration Source Extension Method:</h4>

        <div class="configuration_info">

            <p>
                At this point we can create an extension method (<a data-toggle="modal" href="#DBConfigurationSourceExtensionsModal"><code>DBConfigurationSourceExtensions</code></a>)
                to add the configuration source at the <code>Program</code> class of our app, so it can run all this code and load the configuration from the database on startup.
                This extension method will return a <code>DBConfigurationSource</code> object.
            </p>
        </div>

    </div>
    <div class="info-col">

        @await Component.InvokeAsync("Code", "Program")

        <h4 class="configuration_info_title">4. Loading Configuration:</h4>

        <div class="configuration_info">
            <p>
                To load this configuration at startup time, all we have to do is create a <code>ConfigurationBuilder</code> object and call our custom <code>AddDBConfigurationProvider()</code>
                method from our <code>DBConfigurationSourceExtensions</code> extension class. This must be done, in the <a data-toggle="modal" href="#ProgramModal"><code>Program</code></a>
                class, in its <code>CreateWebHostBuilder().ConfigureAppConfiguration</code> method, and after the automatic default loading of the configuration, so we can access
                the <code>connectionstring</code> for our configuration database that must be stored in one of the <code>appsettings.json</code> files.
            </p>
        </div>
    </div>
</div>


<div class="info-row">
    <div class="info-col-fullrow">

        <h4 class="configuration_info_title">5. Using Configuration:</h4>

        <div class="configuration_info">
            <p>
                Once the configuration is loaded into the application, we can access it as any other configuration. I prefer injecting an <code>IConfiguration _configuration</code> object
                into any class constructor, and from there manipulate to render/use its information in the views.
            </p>
        </div>


    </div>

</div>

ConfigurationWeb/Views/DB/Departments.cshtml
@model List<Configuration.Data.Models.Department>

@{
    ViewData["Title"] = "Departments";
}


    <div class="info-row">

        <div class="info-col">

            <h2 class="configuration_info_title">DB configuration - loading a list of Departments:</h2>

            <div class="configuration_info">
                <p>

                    After loading all the configuration information from the database into the app configuration through the <code>Program</code> class, in its
                    <code>CreateWebHostBuilder().ConfigureAppConfiguration</code> method while the app is starting up, as described
                    <a asp-controller="DB" asp-action="DBInfo">here</a>, it is available for the application to use as any other loaded configuration.
                </p>
                <p>
                    Then the configuration info can be used from anywhere in the app, by injecting a configuration (<code>IConfiguration _configuration</code>) object into the class constructor.
                    From there the info is available to be used throughout the class.
                </p>
                <p>
                    For rendering, the configuration info is loaded here by injecting an <code>IConfiguration</code> object to the controller constructor and loading the info into a
                    <code>List<<Text>Department</Text>></code> object, using:
                    <ol>
                        <li><code> _configuration.GetSection("Complex:Department").GetChildren()</code></li>
                        <li><code>new List<<text>Department</text>>().Add(new Department { Name = item.Key, Description = item.Value })</code></li>
                    </ol>
                    Then all that is left to do is pass the <code>List<<text>Department</text>></code> object to the view for rendering.
                </p>
            </div>

        </div>

        <div class="info-col info-col-card">

            <div class="card-size">
                <div class="card-header">
                    <h5><b>DB configuration - loading Departments:</b></h5>
                </div>
                <div class="card-body">

                    @foreach (var item in Model)
                    {
                        <p class="list-group-item"><b>@item.Name: </b> @item.Description</p>
                    }

                </div>
            </div>

        </div>

    </div>

ConfigurationWeb/Views/DB/Index.cshtml
@model Dictionary<string, string>
@{
    ViewData["Title"] = "Basic DB";
}

    <div class="info-row">

        <div class="info-col">

            <h2 class="configuration_info_title">Basic DB configuration loading:</h2>

            <div class="configuration_info">
                <p>

                    After loading all the configuration information from the database into the app configuration through the <code>Program</code> class, in its
                    <code>CreateWebHostBuilder().ConfigureAppConfiguration</code> method while the app is starting up, as described 
                    <a asp-controller="DB" asp-action="DBInfo">here</a>, it is available for the application to use as any other loaded configuration.
                </p>
                <p>
                    Then the configuration info can be used from anywhere in the app, by injecting a configuration (<code>IConfiguration _configuration</code>) object into the class 
                    constructor. From there the info is available to be used throughout the class.
                </p>
                <p>
                    For rendering, the configuration info is loaded here by injecting an <code>IConfiguration</code> object to the controller constructor and loading the info into a
                    <code>Dictionary<<text>string, string</text>></code> object, using the <code> _configuration.GetValue<<text>string</text>>(key))</code> method, and passing the 
                    <code>Dictionary</code> object to the view.
                </p>
            </div>

        </div>

        <div class="info-col info-col-card">

            <div class="card-size">
                <div class="card-header">
                    <h5><b>Basic DB configuration loading:</b></h5>
                </div>
                <div class="card-body">

                    @foreach (var item in Model)
                    {
                        <p class="list-group-item"><b>@item.Key: </b> @item.Value </p>
                    }

                </div>
            </div>

        </div>

    </div>

ConfigurationWeb/Views/Home/Contact.cshtml
@model ContactViewModel

<!-- Access the configuration injecting an IConfiguration object into the view directly -->
@inject IConfiguration  configuration

@{
    ViewData["Title"] = "Contact";
}

<div class="info-row">

    <div class="info-col">

        <h2 class="configuration_info_title">Contact</h2>

        <div class="configuration_info">
            <p>
                The configuration is defined in a custom configuration file (<code>Contact.json</code>), and added to the application configuration in
                <code>Program.ConfigureAppConfiguration()</code>, while the app is starting up.
            </p>
            <p>
                Then the configuration info can be used from anywhere in the app, by injecting a configuration (<code>IConfiguration _configuration</code>) object into the class constructor. From there
                the info is available to be used throughout the class.
            </p>
            <p>
                For rendering, the configuration information is loaded into a <code>ViewModel (ContactViewModel)</code> from the <code>Contact</code> action in the <code>Home</code> controller:
                <code>_configuration.GetSection("Contact").Get<<text>ContactViewModel</text>>()</code>.
            </p>
            <p>
                For the last message (Message), the info has been loaded at app startup from <code>appsettings.json</code>, and injected directly onto the view <code>Contant</code> using the 
                <code>@@inject</code> directive: <code>@@inject IConfiguration  configuration</code>). Then the configuration is available in the view for rendering its info: 
                <code>@@configuration["ContactMessage"]</code>.

            </p>
        </div>

    </div>

    <div class="info-col info-col-card">

        <div class="card-size">
            <div class="card-header">
                <h5><b>Contact Information:</b></h5>
            </div>
            <div class="card-body">
                <p class="list-group-item"><b>Name: </b> @Model.Name </p>
                <p class="list-group-item"><b>Position: </b> @Model.Position </p>
                <p class="list-group-item"><b>Email: </b> @Model.Email </p>
                <p class="list-group-item"><b>Street: </b> @Model.Street </p>
                <p class="list-group-item"><b>City: </b> @Model.City </p>
                <p class="list-group-item"><b>State: </b> @Model.State </p>
                <p class="list-group-item"><b>Zipcode: </b> @Model.Zipcode </p>
                <!-- Read the configuration key using the IConfiguration object injected into the view directly -->
                <p class="list-group-item  message-color"><b>Message:</b> @configuration["ContactMessage"]</p>
            </div>
        </div>

    </div>

</div>

ConfigurationWeb/Views/Shared/_Layout.OLD.cshtml
<!DOCTYPE html>
<html>

<head>
    <title>
        @ViewBag.Title
    </title>

    <!-- Title icon -->
    <link rel="shortcut icon" type="image/x-icon" href="~/images/configuratorIcon.ico" />

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap 4.3.1 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Work+Sans|Roboto" rel="stylesheet">
    <!--Font Awesome-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
          integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <!-- Custom CSS -->
    <link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/footer-alignment.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/footer.css" asp-append-version="true" />
</head>

<body>
    @*------------------------ aqua ------------------------*@

        <!-- Main body container for top position -->
        <div class="content-wrapper-top">
            @*------------------------ carmesi ------------------------*@

            <!-- NavBar -->
            <div class="col header-footer-background">
                @*------------------------ blue ------------------------*@
                <nav class="navbar navbar-expand-md navbar-light">
                    @*------------------------ maroon ------------------------*@
                    <a class="navbar-brand pb-3 pt-2 logo-position" asp-controller="Home" asp-action="Index">
                        <img src="~/images/logo.png">
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarMenu" style="background-color: yellow;">
                        <span><img class="navbar-icon-custom" src="~/images/key.png"></span>
                    </button>
                    <div class="collapse navbar-collapse header-font" id="navbarMenu">
                        @*------------------------ beige ------------------------*@
                        <ul class="navbar-nav mr-0 pt-3">
                            <li class="nav-item"><a asp-controller="Home" asp-action="Index"> Home </a></li>
                            <li class="nav-item"><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                            <li class="nav-item"><a asp-controller="Home" asp-action="Team">Team</a></li>
                            <li class="nav-item"><a asp-controller="Home" asp-action="Customer">Customer</a></li>
                            <li class="nav-item">
                                <a class="dropdown dropdown-toggle" data-toggle="dropdown" id="dropdownDB" asp-controller="DB" asp-action="DBInfo">
                                    <i class="fa fa-database fa-fw" aria-hidden="true"></i>&nbsp;Database
                                </a>
                                <div class="dropdown-menu" aria-labelledby="dropdownDB">
                                    <a class="column-item" asp-controller="DB" asp-action="DBInfo">DB Intro</a>
                                    <a class="column-item" asp-controller="DB" asp-action="Index">Basic DB</a>
                                    <a class="column-item" asp-controller="DB" asp-action="ComplexObject">Complex Object</a>
                                    <a class="column-item" asp-controller="DB" asp-action="Departments">Departments</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </nav>
            </div>


            <!-- Main content -->
            <div class="row pb-5 main-content-vertical-position">
                <div class="col-md-1"></div>
                <div class="col-md-10">

                    @RenderBody()

                </div>
                <div class="col-md-1"></div>
            </div>

        </div>

        <!-- Footer -->
        <footer class="footer-bottom header-footer-background">

            <div class="footer-row">
                <div class="footer-col footer-col-left">
                    <!-- Logo -->
                    <img src="~/images/logo.png">
                </div>
            </div>

            <div class="footer-row">

                <div class="footer-col footer-col-left">
                    <!-- Footer menu -->
                    <nav class="nav">
                        <a class="nav-link" asp-controller="Home" asp-action="Index"> Home </a>
                        <a class="nav-link" asp-controller="Home" asp-action="Contact">Contact</a>
                        <a class="nav-link" asp-controller="Home" asp-action="Team">Team</a>
                        <a class="nav-link" asp-controller="Home" asp-action="Customer">Customer</a>
                        <a class="nav-link" asp-controller="DB" asp-action="DBInfo">DB Intro</a>
                        <a class="nav-link" asp-controller="DB" asp-action="Index">Basic DB</a>
                        <a class="nav-link" asp-controller="DB" asp-action="ComplexObject">Complex Object</a>
                        <a class="nav-link" asp-controller="DB" asp-action="Departments">Departments</a>
                    </nav>
                </div>

                <div class="footer-col footer-col-center">
                    <!-- Address + contact email -->
                    <div class="footer-col-center-address">
                        <i class="fas fa-map-marker-alt fa-2x middle"></i>
                        &nbsp;
                        1234 21<sup>st</sup> Street, NW <span class="second-line"> Washington, DC USA</span>
                    </div>
                    <div class="footer-col-center-address">
                        <i class="fas fa-phone-square fa-2x"></i>
                        &nbsp;
                        +1 000 123 0000
                    </div>
                    <div class="footer-col-center-address">
                        <i class="fas fa-envelope fa-2x"></i>
                        &nbsp;
                        contact@configurator.com
                    </div>
                </div>

                <div class="footer-col footer-col-right">
                    <!-- Brief description about company + social media logos -->
                    <p>
                        About Configurator Inc: <br>
                        One goal, one passion - configuration.
                    </p>
                    <div>
                        <i class="fab fa-facebook fa-2x"></i>
                        <i class="fab fa-twitter-square fa-2x"></i>
                        <i class="fab fa-linkedin fa-2x"></i>
                        <i class="fab fa-github-square fa-2x"></i>
                    </div>
                </div>

            </div>

            <div class="footer-row-bottom">
                <div class="footer-col footer-col-center">
                    <div class="footer-bottom-col">
                        <p class="text-center">
                            <i class="far fa-copyright"></i> Configurator 2019
                        </p>
                    </div>
                </div>
            </div>

        </footer>


    <!-- jQuery, Popper and Bootstrap js -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
</body>
</html>